// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var Belt_List = require("rescript/lib/js/belt_List.js");
var Js_vector = require("rescript/lib/js/js_vector.js");
var Belt_Array = require("rescript/lib/js/belt_Array.js");
var Belt_SetString = require("rescript/lib/js/belt_SetString.js");

var input = Fs.readFileSync("input/Week1/Year2020Day6.txt", "utf8");

console.log(Belt_List.reduce(Belt_List.map(Js_vector.toList(input.split("\n\n")), (function (g) {
                return Belt_SetString.size(Belt_SetString.fromArray(Belt_Array.keep(g.split(""), (function (s) {
                                      return s !== "\n";
                                    }))));
              })), 0, (function (acc, a) {
            return acc + a | 0;
          })));

console.log(Belt_Array.reduce(Belt_Array.map(input.split("\n\n"), (function (group) {
                var people = Belt_Array.map(Belt_Array.map(group.split("\n"), (function (str) {
                            return str.split("");
                          })), Belt_SetString.fromArray);
                var initSet = Belt_SetString.fromArray(["a...z"]);
                return Belt_SetString.size(Belt_Array.reduce(people, initSet, Belt_SetString.intersect));
              })), 0, (function (acc, a) {
            return acc + a | 0;
          })));

exports.input = input;
/* input Not a pure module */
