// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var Belt_Array = require("rescript/lib/js/belt_Array.js");
var Caml_array = require("rescript/lib/js/caml_array.js");

var input = Fs.readFileSync("input/Week1/Year2020Day5.txt", "utf8");

var bPass = Belt_Array.keep(input.split("\n"), (function (b) {
        return b !== "";
      }));

function getRow(b) {
  return b.substring(0, 7);
}

function getColumn(b) {
  return b.substr(-3);
}

function getLocNumber(bSub, lowerStr, limit) {
  var range = Belt_Array.reduce(bSub.split(""), [
        0,
        limit
      ], (function (acc, str) {
          var mid = (Caml_array.get(acc, 0) + Caml_array.get(acc, 1) | 0) / 2 | 0;
          if (str === lowerStr) {
            return [
                    Caml_array.get(acc, 0),
                    mid
                  ];
          } else {
            return [
                    mid + 1 | 0,
                    Caml_array.get(acc, 1)
                  ];
          }
        }));
  return Caml_array.get(range, 1);
}

var result = Belt_Array.reduce(Belt_Array.map(bPass, (function (b) {
            var row = getLocNumber(b.substring(0, 7), "F", 127);
            var col = getLocNumber(b.substr(-3), "L", 7);
            return (row << 3) + col | 0;
          })), 0, (function (acc, id) {
        if (acc > id) {
          return acc;
        } else {
          return id;
        }
      }));

console.log(result);

exports.input = input;
exports.bPass = bPass;
exports.getRow = getRow;
exports.getColumn = getColumn;
exports.getLocNumber = getLocNumber;
exports.result = result;
/* input Not a pure module */
